# data parameters
name: 's3dis' # data folder
root: 'data/stanford_indoor3d/'
labels: 
  0 : 'ceiling'
  1 : 'floor'
  2 : 'wall'
  3 : 'beam'
  4 : 'column'
  5 : 'window'
  6 : 'door'
  7 : 'table'
  8 : 'chair'
  9 : 'sofa'
  10: 'bookcase'
  11: 'board'
  12: 'clutter'

color_map: # bgr
  0 : [0,255,0]
  1 : [0,0,255]
  2 : [0,255,255]
  3 : [255,255,0]
  4 : [255,0,255]
  5 : [100,100,255]
  6 : [200,200,100]
  7 : [170,120,200]
  8 : [255,0,0]
  9 : [200,100,100]
  10: [10,200,100]
  11: [200,200,200]
  12: [50,50,50]