# training parameters
train:
  model: 'pointnet_sem_seg_light' # model name
  batch_size: 20 # batch size during training
  epochs: 128 # epoch to run
  lr: 0.001 # initial learning rate
  lr_decay: 0.7 # decay rate for lr decay
  step_size: 10 # decay step for lr decay
  weight_decay: 0.0001 # weight decay
  optimizer: 'Adam' # Adam or SGD
  npoint: 4096 # point Number

# testing parameters
test:
  area: 4 # Which area to use for test, option: 1-6
  batch_size: 3
  shuffle: False
  num_workers: 4

  # data parameters
data:
  name: 's3dis' # data folder
  debug_mode: True # if true, small data is used